"""membuat table user

Revision ID: b54d25bcf497
Revises: 
Create Date: 2026-02-18 13:54:07.914193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b54d25bcf497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_obat_hasil_preprocessing_ver_4_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_obat_hasil_preprocessing_ver_4_3',
    sa.Column('COL 1', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('COL 2', mysql.VARCHAR(length=37), nullable=True),
    sa.Column('COL 3', mysql.VARCHAR(length=35), nullable=True),
    sa.Column('COL 4', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('COL 5', mysql.VARCHAR(length=211), nullable=True),
    sa.Column('COL 6', mysql.VARCHAR(length=267), nullable=True),
    sa.Column('COL 7', mysql.VARCHAR(length=495), nullable=True),
    sa.Column('COL 8', mysql.VARCHAR(length=909), nullable=True),
    sa.Column('COL 9', mysql.VARCHAR(length=1450), nullable=True),
    sa.Column('COL 10', mysql.VARCHAR(length=151), nullable=True),
    sa.Column('COL 11', mysql.VARCHAR(length=94), nullable=True),
    sa.Column('COL 12', mysql.VARCHAR(length=613), nullable=True),
    sa.Column('COL 13', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('COL 14', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('COL 15', mysql.VARCHAR(length=84), nullable=True),
    sa.Column('COL 16', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('COL 17', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('COL 18', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('COL 19', mysql.VARCHAR(length=1422), nullable=True),
    sa.Column('COL 20', mysql.VARCHAR(length=157), nullable=True),
    sa.Column('COL 21', mysql.VARCHAR(length=88), nullable=True),
    sa.Column('COL 22', mysql.VARCHAR(length=577), nullable=True),
    sa.Column('COL 23', mysql.VARCHAR(length=187), nullable=True),
    sa.Column('COL 24', mysql.VARCHAR(length=19), nullable=True),
    sa.Column('COL 25', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('COL 26', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('COL 27', mysql.VARCHAR(length=155), nullable=True),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
